# Configuration File for YSEQ Pipeline

# General Settings
MAPPER: "bwa"          # Choose the mapper between "bwa" or "minimap2"
READS: "short"         # Choose read type between "short" or "nanopore"
READS_TYPE: "paired"   # Choose between "single" or "paired" end reads

# Paths
SAMPLE_PATH: "resources/sample"  # Directory for your sample fastq files
OUTDIR: "results/"               # Path for your results directory
TMP_PATH: "resources/tmp"        # Path for temporary files
ENV_PATH: "workflow/envs"        # Path for different environments

# Results
results_refseq: "results"        # Path for reference sequence results

# Additional Comments
# Add any additional configuration options or comments here