# Configuration File for YSEQ Pipeline

# General Settings
MAPPER: "bwa"          # Choose the mapper between "bwa" or "minimap2"
READS: "short"         # Choose read type between "short" or "nanopore"
READS_TYPE: "paired"   # Choose between "single" or "paired" end reads

# Paths
SAMPLE_PATH: "resources/sample"  # Directory for your sample fastq files  
TMP_PATH: "resources/tmp"        # Path for temporary files
REF_PATH: "resources/refseq"     # Path for reference sequence
RESULTS_PATH: "results"        # Path for reference sequence results
LOG_PATH: "log"       # Path for log files
